# Generated by Django 4.2.13 on 2024-07-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Citizen_back',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Citizen_front',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads'),
        ),
    ]
