# Generated by Django 5.0.6 on 2024-06-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.FileField(upload_to='static/uploads'),
        ),
    ]
