# Generated by Django 5.0.6 on 2024-06-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userprofile_citizen_back_userprofile_citizen_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
