# Generated by Django 5.0.6 on 2024-06-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_room_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('HOME', 'HOME'), ('FLAT', 'FLAT'), ('ROOM', 'ROOM')], max_length=250),
        ),
    ]
