# Generated by Django 5.0.6 on 2024-06-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='passwrod',
            new_name='password',
        ),
    ]
