# Generated by Django 5.0.6 on 2024-06-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_passwrod_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Citizen_back',
            field=models.ImageField(blank=True, null=True, upload_to='static/UploadCitizen'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Citizen_front',
            field=models.ImageField(blank=True, null=True, upload_to='static/UploadCitizen'),
        ),
    ]
